import { Country } from '../../shared/types';

// Full list of all countries with their ISO codes and continents
export const getAllCountries = (): Country[] => {
  return [
    // Africa
    { code: 'DZA', name: 'Algeria', visits: [], continent: 'Africa' },
    { code: 'AGO', name: 'Angola', visits: [], continent: 'Africa' },
    { code: 'BEN', name: 'Benin', visits: [], continent: 'Africa' },
    { code: 'BWA', name: 'Botswana', visits: [], continent: 'Africa' },
    { code: 'BFA', name: 'Burkina Faso', visits: [], continent: 'Africa' },
    { code: 'BDI', name: 'Burundi', visits: [], continent: 'Africa' },
    { code: 'CMR', name: 'Cameroon', visits: [], continent: 'Africa' },
    { code: 'CPV', name: 'Cape Verde', visits: [], continent: 'Africa' },
    { code: 'CAF', name: 'Central African Republic', visits: [], continent: 'Africa' },
    { code: 'TCD', name: 'Chad', visits: [], continent: 'Africa' },
    { code: 'COM', name: 'Comoros', visits: [], continent: 'Africa' },
    { code: 'COG', name: 'Republic of the Congo', visits: [], continent: 'Africa' },
    { code: 'COD', name: 'Democratic Republic of the Congo', visits: [], continent: 'Africa' },
    { code: 'CIV', name: "Côte d'Ivoire", visits: [], continent: 'Africa' },
    { code: 'DJI', name: 'Djibouti', visits: [], continent: 'Africa' },
    { code: 'EGY', name: 'Egypt', visits: [], continent: 'Africa' },
    { code: 'GNQ', name: 'Equatorial Guinea', visits: [], continent: 'Africa' },
    { code: 'ERI', name: 'Eritrea', visits: [], continent: 'Africa' },
    { code: 'ETH', name: 'Ethiopia', visits: [], continent: 'Africa' },
    { code: 'GAB', name: 'Gabon', visits: [], continent: 'Africa' },
    { code: 'GMB', name: 'Gambia', visits: [], continent: 'Africa' },
    { code: 'GHA', name: 'Ghana', visits: [], continent: 'Africa' },
    { code: 'GIN', name: 'Guinea', visits: [], continent: 'Africa' },
    { code: 'GNB', name: 'Guinea-Bissau', visits: [], continent: 'Africa' },
    { code: 'KEN', name: 'Kenya', visits: [], continent: 'Africa' },
    { code: 'LSO', name: 'Lesotho', visits: [], continent: 'Africa' },
    { code: 'LBR', name: 'Liberia', visits: [], continent: 'Africa' },
    { code: 'LBY', name: 'Libya', visits: [], continent: 'Africa' },
    { code: 'MDG', name: 'Madagascar', visits: [], continent: 'Africa' },
    { code: 'MWI', name: 'Malawi', visits: [], continent: 'Africa' },
    { code: 'MLI', name: 'Mali', visits: [], continent: 'Africa' },
    { code: 'MRT', name: 'Mauritania', visits: [], continent: 'Africa' },
    { code: 'MUS', name: 'Mauritius', visits: [], continent: 'Africa' },
    { code: 'MAR', name: 'Morocco', visits: [], continent: 'Africa' },
    { code: 'MOZ', name: 'Mozambique', visits: [], continent: 'Africa' },
    { code: 'NAM', name: 'Namibia', visits: [], continent: 'Africa' },
    { code: 'NER', name: 'Niger', visits: [], continent: 'Africa' },
    { code: 'NGA', name: 'Nigeria', visits: [], continent: 'Africa' },
    { code: 'RWA', name: 'Rwanda', visits: [], continent: 'Africa' },
    { code: 'STP', name: 'São Tomé and Príncipe', visits: [], continent: 'Africa' },
    { code: 'SEN', name: 'Senegal', visits: [], continent: 'Africa' },
    { code: 'SYC', name: 'Seychelles', visits: [], continent: 'Africa' },
    { code: 'SLE', name: 'Sierra Leone', visits: [], continent: 'Africa' },
    { code: 'SOM', name: 'Somalia', visits: [], continent: 'Africa' },
    { code: 'ZAF', name: 'South Africa', visits: [], continent: 'Africa' },
    { code: 'SSD', name: 'South Sudan', visits: [], continent: 'Africa' },
    { code: 'SDN', name: 'Sudan', visits: [], continent: 'Africa' },
    { code: 'SWZ', name: 'Eswatini', visits: [], continent: 'Africa' },
    { code: 'TZA', name: 'Tanzania', visits: [], continent: 'Africa' },
    { code: 'TGO', name: 'Togo', visits: [], continent: 'Africa' },
    { code: 'TUN', name: 'Tunisia', visits: [], continent: 'Africa' },
    { code: 'UGA', name: 'Uganda', visits: [], continent: 'Africa' },
    { code: 'ZMB', name: 'Zambia', visits: [], continent: 'Africa' },
    { code: 'ZWE', name: 'Zimbabwe', visits: [], continent: 'Africa' },

    // Asia
    { code: 'AFG', name: 'Afghanistan', visits: [], continent: 'Asia' },
    { code: 'ARM', name: 'Armenia', visits: [], continent: 'Asia' },
    { code: 'AZE', name: 'Azerbaijan', visits: [], continent: 'Asia' },
    { code: 'BHR', name: 'Bahrain', visits: [], continent: 'Asia' },
    { code: 'BGD', name: 'Bangladesh', visits: [], continent: 'Asia' },
    { code: 'BTN', name: 'Bhutan', visits: [], continent: 'Asia' },
    { code: 'BRN', name: 'Brunei', visits: [], continent: 'Asia' },
    { code: 'KHM', name: 'Cambodia', visits: [], continent: 'Asia' },
    { code: 'CHN', name: 'China', visits: [], continent: 'Asia' },
    { code: 'GEO', name: 'Georgia', visits: [], continent: 'Asia' },
    { code: 'IND', name: 'India', visits: [], continent: 'Asia' },
    { code: 'IDN', name: 'Indonesia', visits: [], continent: 'Asia' },
    { code: 'IRN', name: 'Iran', visits: [], continent: 'Asia' },
    { code: 'IRQ', name: 'Iraq', visits: [], continent: 'Asia' },
    { code: 'ISR', name: 'Israel', visits: [], continent: 'Asia' },
    { code: 'JPN', name: 'Japan', visits: [], continent: 'Asia' },
    { code: 'JOR', name: 'Jordan', visits: [], continent: 'Asia' },
    { code: 'KAZ', name: 'Kazakhstan', visits: [], continent: 'Asia' },
    { code: 'KWT', name: 'Kuwait', visits: [], continent: 'Asia' },
    { code: 'KGZ', name: 'Kyrgyzstan', visits: [], continent: 'Asia' },
    { code: 'LAO', name: 'Laos', visits: [], continent: 'Asia' },
    { code: 'LBN', name: 'Lebanon', visits: [], continent: 'Asia' },
    { code: 'MYS', name: 'Malaysia', visits: [], continent: 'Asia' },
    { code: 'MDV', name: 'Maldives', visits: [], continent: 'Asia' },
    { code: 'MNG', name: 'Mongolia', visits: [], continent: 'Asia' },
    { code: 'MMR', name: 'Myanmar', visits: [], continent: 'Asia' },
    { code: 'NPL', name: 'Nepal', visits: [], continent: 'Asia' },
    { code: 'PRK', name: 'North Korea', visits: [], continent: 'Asia' },
    { code: 'OMN', name: 'Oman', visits: [], continent: 'Asia' },
    { code: 'PAK', name: 'Pakistan', visits: [], continent: 'Asia' },
    { code: 'PSE', name: 'Palestine', visits: [], continent: 'Asia' },
    { code: 'PHL', name: 'Philippines', visits: [], continent: 'Asia' },
    { code: 'QAT', name: 'Qatar', visits: [], continent: 'Asia' },
    { code: 'SAU', name: 'Saudi Arabia', visits: [], continent: 'Asia' },
    { code: 'SGP', name: 'Singapore', visits: [], continent: 'Asia' },
    { code: 'KOR', name: 'South Korea', visits: [], continent: 'Asia' },
    { code: 'LKA', name: 'Sri Lanka', visits: [], continent: 'Asia' },
    { code: 'SYR', name: 'Syria', visits: [], continent: 'Asia' },
    { code: 'TWN', name: 'Taiwan', visits: [], continent: 'Asia' },
    { code: 'TJK', name: 'Tajikistan', visits: [], continent: 'Asia' },
    { code: 'THA', name: 'Thailand', visits: [], continent: 'Asia' },
    { code: 'TLS', name: 'Timor-Leste', visits: [], continent: 'Asia' },
    { code: 'TUR', name: 'Turkey', visits: [], continent: 'Asia' },
    { code: 'TKM', name: 'Turkmenistan', visits: [], continent: 'Asia' },
    { code: 'ARE', name: 'United Arab Emirates', visits: [], continent: 'Asia' },
    { code: 'UZB', name: 'Uzbekistan', visits: [], continent: 'Asia' },
    { code: 'VNM', name: 'Vietnam', visits: [], continent: 'Asia' },
    { code: 'YEM', name: 'Yemen', visits: [], continent: 'Asia' },

    // Europe
    { code: 'ALB', name: 'Albania', visits: [], continent: 'Europe' },
    { code: 'AND', name: 'Andorra', visits: [], continent: 'Europe' },
    { code: 'AUT', name: 'Austria', visits: [], continent: 'Europe' },
    { code: 'BLR', name: 'Belarus', visits: [], continent: 'Europe' },
    { code: 'BEL', name: 'Belgium', visits: [], continent: 'Europe' },
    { code: 'BIH', name: 'Bosnia and Herzegovina', visits: [], continent: 'Europe' },
    { code: 'BGR', name: 'Bulgaria', visits: [], continent: 'Europe' },
    { code: 'HRV', name: 'Croatia', visits: [], continent: 'Europe' },
    { code: 'CYP', name: 'Cyprus', visits: [], continent: 'Europe' },
    { code: 'CZE', name: 'Czech Republic', visits: [], continent: 'Europe' },
    { code: 'DNK', name: 'Denmark', visits: [], continent: 'Europe' },
    { code: 'EST', name: 'Estonia', visits: [], continent: 'Europe' },
    { code: 'FIN', name: 'Finland', visits: [], continent: 'Europe' },
    { code: 'FRA', name: 'France', visits: [], continent: 'Europe' },
    { code: 'DEU', name: 'Germany', visits: [], continent: 'Europe' },
    { code: 'GRC', name: 'Greece', visits: [], continent: 'Europe' },
    { code: 'HUN', name: 'Hungary', visits: [], continent: 'Europe' },
    { code: 'ISL', name: 'Iceland', visits: [], continent: 'Europe' },
    { code: 'IRL', name: 'Ireland', visits: [], continent: 'Europe' },
    { code: 'ITA', name: 'Italy', visits: [], continent: 'Europe' },
    { code: 'XKX', name: 'Kosovo', visits: [], continent: 'Europe' },
    { code: 'LVA', name: 'Latvia', visits: [], continent: 'Europe' },
    { code: 'LIE', name: 'Liechtenstein', visits: [], continent: 'Europe' },
    { code: 'LTU', name: 'Lithuania', visits: [], continent: 'Europe' },
    { code: 'LUX', name: 'Luxembourg', visits: [], continent: 'Europe' },
    { code: 'MKD', name: 'North Macedonia', visits: [], continent: 'Europe' },
    { code: 'MLT', name: 'Malta', visits: [], continent: 'Europe' },
    { code: 'MDA', name: 'Moldova', visits: [], continent: 'Europe' },
    { code: 'MCO', name: 'Monaco', visits: [], continent: 'Europe' },
    { code: 'MNE', name: 'Montenegro', visits: [], continent: 'Europe' },
    { code: 'NLD', name: 'Netherlands', visits: [], continent: 'Europe' },
    { code: 'NOR', name: 'Norway', visits: [], continent: 'Europe' },
    { code: 'POL', name: 'Poland', visits: [], continent: 'Europe' },
    { code: 'PRT', name: 'Portugal', visits: [], continent: 'Europe' },
    { code: 'ROU', name: 'Romania', visits: [], continent: 'Europe' },
    { code: 'RUS', name: 'Russia', visits: [], continent: 'Europe' },
    { code: 'SMR', name: 'San Marino', visits: [], continent: 'Europe' },
    { code: 'SRB', name: 'Serbia', visits: [], continent: 'Europe' },
    { code: 'SVK', name: 'Slovakia', visits: [], continent: 'Europe' },
    { code: 'SVN', name: 'Slovenia', visits: [], continent: 'Europe' },
    { code: 'ESP', name: 'Spain', visits: [], continent: 'Europe' },
    { code: 'SWE', name: 'Sweden', visits: [], continent: 'Europe' },
    { code: 'CHE', name: 'Switzerland', visits: [], continent: 'Europe' },
    { code: 'UKR', name: 'Ukraine', visits: [], continent: 'Europe' },
    { code: 'GBR', name: 'United Kingdom', visits: [], continent: 'Europe' },
    { code: 'VAT', name: 'Vatican City', visits: [], continent: 'Europe' },

    // North America
    { code: 'ATG', name: 'Antigua and Barbuda', visits: [], continent: 'North America' },
    { code: 'BHS', name: 'Bahamas', visits: [], continent: 'North America' },
    { code: 'BRB', name: 'Barbados', visits: [], continent: 'North America' },
    { code: 'BLZ', name: 'Belize', visits: [], continent: 'North America' },
    { code: 'CAN', name: 'Canada', visits: [], continent: 'North America' },
    { code: 'CRI', name: 'Costa Rica', visits: [], continent: 'North America' },
    { code: 'CUB', name: 'Cuba', visits: [], continent: 'North America' },
    { code: 'DMA', name: 'Dominica', visits: [], continent: 'North America' },
    { code: 'DOM', name: 'Dominican Republic', visits: [], continent: 'North America' },
    { code: 'SLV', name: 'El Salvador', visits: [], continent: 'North America' },
    { code: 'GRD', name: 'Grenada', visits: [], continent: 'North America' },
    { code: 'GTM', name: 'Guatemala', visits: [], continent: 'North America' },
    { code: 'HTI', name: 'Haiti', visits: [], continent: 'North America' },
    { code: 'HND', name: 'Honduras', visits: [], continent: 'North America' },
    { code: 'JAM', name: 'Jamaica', visits: [], continent: 'North America' },
    { code: 'MEX', name: 'Mexico', visits: [], continent: 'North America' },
    { code: 'NIC', name: 'Nicaragua', visits: [], continent: 'North America' },
    { code: 'PAN', name: 'Panama', visits: [], continent: 'North America' },
    { code: 'KNA', name: 'Saint Kitts and Nevis', visits: [], continent: 'North America' },
    { code: 'LCA', name: 'Saint Lucia', visits: [], continent: 'North America' },
    { code: 'VCT', name: 'Saint Vincent and the Grenadines', visits: [], continent: 'North America' },
    { code: 'TTO', name: 'Trinidad and Tobago', visits: [], continent: 'North America' },
    { code: 'USA', name: 'United States', visits: [], continent: 'North America' },

    // South America
    { code: 'ARG', name: 'Argentina', visits: [], continent: 'South America' },
    { code: 'BOL', name: 'Bolivia', visits: [], continent: 'South America' },
    { code: 'BRA', name: 'Brazil', visits: [], continent: 'South America' },
    { code: 'CHL', name: 'Chile', visits: [], continent: 'South America' },
    { code: 'COL', name: 'Colombia', visits: [], continent: 'South America' },
    { code: 'ECU', name: 'Ecuador', visits: [], continent: 'South America' },
    { code: 'GUY', name: 'Guyana', visits: [], continent: 'South America' },
    { code: 'PRY', name: 'Paraguay', visits: [], continent: 'South America' },
    { code: 'PER', name: 'Peru', visits: [], continent: 'South America' },
    { code: 'SUR', name: 'Suriname', visits: [], continent: 'South America' },
    { code: 'URY', name: 'Uruguay', visits: [], continent: 'South America' },
    { code: 'VEN', name: 'Venezuela', visits: [], continent: 'South America' },

    // Oceania
    { code: 'AUS', name: 'Australia', visits: [], continent: 'Oceania' },
    { code: 'FJI', name: 'Fiji', visits: [], continent: 'Oceania' },
    { code: 'KIR', name: 'Kiribati', visits: [], continent: 'Oceania' },
    { code: 'MHL', name: 'Marshall Islands', visits: [], continent: 'Oceania' },
    { code: 'FSM', name: 'Micronesia', visits: [], continent: 'Oceania' },
    { code: 'NRU', name: 'Nauru', visits: [], continent: 'Oceania' },
    { code: 'NZL', name: 'New Zealand', visits: [], continent: 'Oceania' },
    { code: 'PLW', name: 'Palau', visits: [], continent: 'Oceania' },
    { code: 'PNG', name: 'Papua New Guinea', visits: [], continent: 'Oceania' },
    { code: 'WSM', name: 'Samoa', visits: [], continent: 'Oceania' },
    { code: 'SLB', name: 'Solomon Islands', visits: [], continent: 'Oceania' },
    { code: 'TON', name: 'Tonga', visits: [], continent: 'Oceania' },
    { code: 'TUV', name: 'Tuvalu', visits: [], continent: 'Oceania' },
    { code: 'VUT', name: 'Vanuatu', visits: [], continent: 'Oceania' },

    // Disputed Territories & Dependencies (optional to track)
    { code: 'GRL', name: 'Greenland', visits: [], continent: 'North America', isTerritory: true },
    { code: 'ESH', name: 'Western Sahara', visits: [], continent: 'Africa', isTerritory: true },
    { code: 'SOL', name: 'Somaliland', visits: [], continent: 'Africa', isTerritory: true },
    { code: 'NCY', name: 'Northern Cyprus', visits: [], continent: 'Europe', isTerritory: true },
    { code: 'ATA', name: 'Antarctica', visits: [], continent: 'Antarctica', isTerritory: true },
  ];
};
