import { Country } from '../../shared/types';

// Full list of all countries with their ISO codes and continents
export const getAllCountries = (): Country[] => {
  return [
    // Africa
    { code: 'DZA', name: 'Algeria', visited: false, continent: 'Africa' },
    { code: 'AGO', name: 'Angola', visited: false, continent: 'Africa' },
    { code: 'BEN', name: 'Benin', visited: false, continent: 'Africa' },
    { code: 'BWA', name: 'Botswana', visited: false, continent: 'Africa' },
    { code: 'BFA', name: 'Burkina Faso', visited: false, continent: 'Africa' },
    { code: 'BDI', name: 'Burundi', visited: false, continent: 'Africa' },
    { code: 'CMR', name: 'Cameroon', visited: false, continent: 'Africa' },
    { code: 'CPV', name: 'Cape Verde', visited: false, continent: 'Africa' },
    { code: 'CAF', name: 'Central African Republic', visited: false, continent: 'Africa' },
    { code: 'TCD', name: 'Chad', visited: false, continent: 'Africa' },
    { code: 'COM', name: 'Comoros', visited: false, continent: 'Africa' },
    { code: 'COG', name: 'Republic of the Congo', visited: false, continent: 'Africa' },
    { code: 'COD', name: 'Democratic Republic of the Congo', visited: false, continent: 'Africa' },
    { code: 'CIV', name: "Côte d'Ivoire", visited: false, continent: 'Africa' },
    { code: 'DJI', name: 'Djibouti', visited: false, continent: 'Africa' },
    { code: 'EGY', name: 'Egypt', visited: false, continent: 'Africa' },
    { code: 'GNQ', name: 'Equatorial Guinea', visited: false, continent: 'Africa' },
    { code: 'ERI', name: 'Eritrea', visited: false, continent: 'Africa' },
    { code: 'ETH', name: 'Ethiopia', visited: false, continent: 'Africa' },
    { code: 'GAB', name: 'Gabon', visited: false, continent: 'Africa' },
    { code: 'GMB', name: 'Gambia', visited: false, continent: 'Africa' },
    { code: 'GHA', name: 'Ghana', visited: false, continent: 'Africa' },
    { code: 'GIN', name: 'Guinea', visited: false, continent: 'Africa' },
    { code: 'GNB', name: 'Guinea-Bissau', visited: false, continent: 'Africa' },
    { code: 'KEN', name: 'Kenya', visited: false, continent: 'Africa' },
    { code: 'LSO', name: 'Lesotho', visited: false, continent: 'Africa' },
    { code: 'LBR', name: 'Liberia', visited: false, continent: 'Africa' },
    { code: 'LBY', name: 'Libya', visited: false, continent: 'Africa' },
    { code: 'MDG', name: 'Madagascar', visited: false, continent: 'Africa' },
    { code: 'MWI', name: 'Malawi', visited: false, continent: 'Africa' },
    { code: 'MLI', name: 'Mali', visited: false, continent: 'Africa' },
    { code: 'MRT', name: 'Mauritania', visited: false, continent: 'Africa' },
    { code: 'MUS', name: 'Mauritius', visited: false, continent: 'Africa' },
    { code: 'MAR', name: 'Morocco', visited: false, continent: 'Africa' },
    { code: 'MOZ', name: 'Mozambique', visited: false, continent: 'Africa' },
    { code: 'NAM', name: 'Namibia', visited: false, continent: 'Africa' },
    { code: 'NER', name: 'Niger', visited: false, continent: 'Africa' },
    { code: 'NGA', name: 'Nigeria', visited: false, continent: 'Africa' },
    { code: 'RWA', name: 'Rwanda', visited: false, continent: 'Africa' },
    { code: 'STP', name: 'São Tomé and Príncipe', visited: false, continent: 'Africa' },
    { code: 'SEN', name: 'Senegal', visited: false, continent: 'Africa' },
    { code: 'SYC', name: 'Seychelles', visited: false, continent: 'Africa' },
    { code: 'SLE', name: 'Sierra Leone', visited: false, continent: 'Africa' },
    { code: 'SOM', name: 'Somalia', visited: false, continent: 'Africa' },
    { code: 'ZAF', name: 'South Africa', visited: false, continent: 'Africa' },
    { code: 'SSD', name: 'South Sudan', visited: false, continent: 'Africa' },
    { code: 'SDN', name: 'Sudan', visited: false, continent: 'Africa' },
    { code: 'SWZ', name: 'Eswatini', visited: false, continent: 'Africa' },
    { code: 'TZA', name: 'Tanzania', visited: false, continent: 'Africa' },
    { code: 'TGO', name: 'Togo', visited: false, continent: 'Africa' },
    { code: 'TUN', name: 'Tunisia', visited: false, continent: 'Africa' },
    { code: 'UGA', name: 'Uganda', visited: false, continent: 'Africa' },
    { code: 'ZMB', name: 'Zambia', visited: false, continent: 'Africa' },
    { code: 'ZWE', name: 'Zimbabwe', visited: false, continent: 'Africa' },

    // Asia
    { code: 'AFG', name: 'Afghanistan', visited: false, continent: 'Asia' },
    { code: 'ARM', name: 'Armenia', visited: false, continent: 'Asia' },
    { code: 'AZE', name: 'Azerbaijan', visited: false, continent: 'Asia' },
    { code: 'BHR', name: 'Bahrain', visited: false, continent: 'Asia' },
    { code: 'BGD', name: 'Bangladesh', visited: false, continent: 'Asia' },
    { code: 'BTN', name: 'Bhutan', visited: false, continent: 'Asia' },
    { code: 'BRN', name: 'Brunei', visited: false, continent: 'Asia' },
    { code: 'KHM', name: 'Cambodia', visited: false, continent: 'Asia' },
    { code: 'CHN', name: 'China', visited: false, continent: 'Asia' },
    { code: 'GEO', name: 'Georgia', visited: false, continent: 'Asia' },
    { code: 'IND', name: 'India', visited: false, continent: 'Asia' },
    { code: 'IDN', name: 'Indonesia', visited: false, continent: 'Asia' },
    { code: 'IRN', name: 'Iran', visited: false, continent: 'Asia' },
    { code: 'IRQ', name: 'Iraq', visited: false, continent: 'Asia' },
    { code: 'ISR', name: 'Israel', visited: false, continent: 'Asia' },
    { code: 'JPN', name: 'Japan', visited: false, continent: 'Asia' },
    { code: 'JOR', name: 'Jordan', visited: false, continent: 'Asia' },
    { code: 'KAZ', name: 'Kazakhstan', visited: false, continent: 'Asia' },
    { code: 'KWT', name: 'Kuwait', visited: false, continent: 'Asia' },
    { code: 'KGZ', name: 'Kyrgyzstan', visited: false, continent: 'Asia' },
    { code: 'LAO', name: 'Laos', visited: false, continent: 'Asia' },
    { code: 'LBN', name: 'Lebanon', visited: false, continent: 'Asia' },
    { code: 'MYS', name: 'Malaysia', visited: false, continent: 'Asia' },
    { code: 'MDV', name: 'Maldives', visited: false, continent: 'Asia' },
    { code: 'MNG', name: 'Mongolia', visited: false, continent: 'Asia' },
    { code: 'MMR', name: 'Myanmar', visited: false, continent: 'Asia' },
    { code: 'NPL', name: 'Nepal', visited: false, continent: 'Asia' },
    { code: 'PRK', name: 'North Korea', visited: false, continent: 'Asia' },
    { code: 'OMN', name: 'Oman', visited: false, continent: 'Asia' },
    { code: 'PAK', name: 'Pakistan', visited: false, continent: 'Asia' },
    { code: 'PSE', name: 'Palestine', visited: false, continent: 'Asia' },
    { code: 'PHL', name: 'Philippines', visited: false, continent: 'Asia' },
    { code: 'QAT', name: 'Qatar', visited: false, continent: 'Asia' },
    { code: 'SAU', name: 'Saudi Arabia', visited: false, continent: 'Asia' },
    { code: 'SGP', name: 'Singapore', visited: false, continent: 'Asia' },
    { code: 'KOR', name: 'South Korea', visited: false, continent: 'Asia' },
    { code: 'LKA', name: 'Sri Lanka', visited: false, continent: 'Asia' },
    { code: 'SYR', name: 'Syria', visited: false, continent: 'Asia' },
    { code: 'TWN', name: 'Taiwan', visited: false, continent: 'Asia' },
    { code: 'TJK', name: 'Tajikistan', visited: false, continent: 'Asia' },
    { code: 'THA', name: 'Thailand', visited: false, continent: 'Asia' },
    { code: 'TLS', name: 'Timor-Leste', visited: false, continent: 'Asia' },
    { code: 'TUR', name: 'Turkey', visited: false, continent: 'Asia' },
    { code: 'TKM', name: 'Turkmenistan', visited: false, continent: 'Asia' },
    { code: 'ARE', name: 'United Arab Emirates', visited: false, continent: 'Asia' },
    { code: 'UZB', name: 'Uzbekistan', visited: false, continent: 'Asia' },
    { code: 'VNM', name: 'Vietnam', visited: false, continent: 'Asia' },
    { code: 'YEM', name: 'Yemen', visited: false, continent: 'Asia' },

    // Europe
    { code: 'ALB', name: 'Albania', visited: false, continent: 'Europe' },
    { code: 'AND', name: 'Andorra', visited: false, continent: 'Europe' },
    { code: 'AUT', name: 'Austria', visited: false, continent: 'Europe' },
    { code: 'BLR', name: 'Belarus', visited: false, continent: 'Europe' },
    { code: 'BEL', name: 'Belgium', visited: false, continent: 'Europe' },
    { code: 'BIH', name: 'Bosnia and Herzegovina', visited: false, continent: 'Europe' },
    { code: 'BGR', name: 'Bulgaria', visited: false, continent: 'Europe' },
    { code: 'HRV', name: 'Croatia', visited: false, continent: 'Europe' },
    { code: 'CYP', name: 'Cyprus', visited: false, continent: 'Europe' },
    { code: 'CZE', name: 'Czech Republic', visited: false, continent: 'Europe' },
    { code: 'DNK', name: 'Denmark', visited: false, continent: 'Europe' },
    { code: 'EST', name: 'Estonia', visited: false, continent: 'Europe' },
    { code: 'FIN', name: 'Finland', visited: false, continent: 'Europe' },
    { code: 'FRA', name: 'France', visited: false, continent: 'Europe' },
    { code: 'DEU', name: 'Germany', visited: false, continent: 'Europe' },
    { code: 'GRC', name: 'Greece', visited: false, continent: 'Europe' },
    { code: 'HUN', name: 'Hungary', visited: false, continent: 'Europe' },
    { code: 'ISL', name: 'Iceland', visited: false, continent: 'Europe' },
    { code: 'IRL', name: 'Ireland', visited: false, continent: 'Europe' },
    { code: 'ITA', name: 'Italy', visited: false, continent: 'Europe' },
    { code: 'XKX', name: 'Kosovo', visited: false, continent: 'Europe' },
    { code: 'LVA', name: 'Latvia', visited: false, continent: 'Europe' },
    { code: 'LIE', name: 'Liechtenstein', visited: false, continent: 'Europe' },
    { code: 'LTU', name: 'Lithuania', visited: false, continent: 'Europe' },
    { code: 'LUX', name: 'Luxembourg', visited: false, continent: 'Europe' },
    { code: 'MKD', name: 'North Macedonia', visited: false, continent: 'Europe' },
    { code: 'MLT', name: 'Malta', visited: false, continent: 'Europe' },
    { code: 'MDA', name: 'Moldova', visited: false, continent: 'Europe' },
    { code: 'MCO', name: 'Monaco', visited: false, continent: 'Europe' },
    { code: 'MNE', name: 'Montenegro', visited: false, continent: 'Europe' },
    { code: 'NLD', name: 'Netherlands', visited: false, continent: 'Europe' },
    { code: 'NOR', name: 'Norway', visited: false, continent: 'Europe' },
    { code: 'POL', name: 'Poland', visited: false, continent: 'Europe' },
    { code: 'PRT', name: 'Portugal', visited: false, continent: 'Europe' },
    { code: 'ROU', name: 'Romania', visited: false, continent: 'Europe' },
    { code: 'RUS', name: 'Russia', visited: false, continent: 'Europe' },
    { code: 'SMR', name: 'San Marino', visited: false, continent: 'Europe' },
    { code: 'SRB', name: 'Serbia', visited: false, continent: 'Europe' },
    { code: 'SVK', name: 'Slovakia', visited: false, continent: 'Europe' },
    { code: 'SVN', name: 'Slovenia', visited: false, continent: 'Europe' },
    { code: 'ESP', name: 'Spain', visited: false, continent: 'Europe' },
    { code: 'SWE', name: 'Sweden', visited: false, continent: 'Europe' },
    { code: 'CHE', name: 'Switzerland', visited: false, continent: 'Europe' },
    { code: 'UKR', name: 'Ukraine', visited: false, continent: 'Europe' },
    { code: 'GBR', name: 'United Kingdom', visited: false, continent: 'Europe' },
    { code: 'VAT', name: 'Vatican City', visited: false, continent: 'Europe' },

    // North America
    { code: 'ATG', name: 'Antigua and Barbuda', visited: false, continent: 'North America' },
    { code: 'BHS', name: 'Bahamas', visited: false, continent: 'North America' },
    { code: 'BRB', name: 'Barbados', visited: false, continent: 'North America' },
    { code: 'BLZ', name: 'Belize', visited: false, continent: 'North America' },
    { code: 'CAN', name: 'Canada', visited: false, continent: 'North America' },
    { code: 'CRI', name: 'Costa Rica', visited: false, continent: 'North America' },
    { code: 'CUB', name: 'Cuba', visited: false, continent: 'North America' },
    { code: 'DMA', name: 'Dominica', visited: false, continent: 'North America' },
    { code: 'DOM', name: 'Dominican Republic', visited: false, continent: 'North America' },
    { code: 'SLV', name: 'El Salvador', visited: false, continent: 'North America' },
    { code: 'GRD', name: 'Grenada', visited: false, continent: 'North America' },
    { code: 'GTM', name: 'Guatemala', visited: false, continent: 'North America' },
    { code: 'HTI', name: 'Haiti', visited: false, continent: 'North America' },
    { code: 'HND', name: 'Honduras', visited: false, continent: 'North America' },
    { code: 'JAM', name: 'Jamaica', visited: false, continent: 'North America' },
    { code: 'MEX', name: 'Mexico', visited: false, continent: 'North America' },
    { code: 'NIC', name: 'Nicaragua', visited: false, continent: 'North America' },
    { code: 'PAN', name: 'Panama', visited: false, continent: 'North America' },
    { code: 'KNA', name: 'Saint Kitts and Nevis', visited: false, continent: 'North America' },
    { code: 'LCA', name: 'Saint Lucia', visited: false, continent: 'North America' },
    { code: 'VCT', name: 'Saint Vincent and the Grenadines', visited: false, continent: 'North America' },
    { code: 'TTO', name: 'Trinidad and Tobago', visited: false, continent: 'North America' },
    { code: 'USA', name: 'United States', visited: false, continent: 'North America' },

    // South America
    { code: 'ARG', name: 'Argentina', visited: false, continent: 'South America' },
    { code: 'BOL', name: 'Bolivia', visited: false, continent: 'South America' },
    { code: 'BRA', name: 'Brazil', visited: false, continent: 'South America' },
    { code: 'CHL', name: 'Chile', visited: false, continent: 'South America' },
    { code: 'COL', name: 'Colombia', visited: false, continent: 'South America' },
    { code: 'ECU', name: 'Ecuador', visited: false, continent: 'South America' },
    { code: 'GUY', name: 'Guyana', visited: false, continent: 'South America' },
    { code: 'PRY', name: 'Paraguay', visited: false, continent: 'South America' },
    { code: 'PER', name: 'Peru', visited: false, continent: 'South America' },
    { code: 'SUR', name: 'Suriname', visited: false, continent: 'South America' },
    { code: 'URY', name: 'Uruguay', visited: false, continent: 'South America' },
    { code: 'VEN', name: 'Venezuela', visited: false, continent: 'South America' },

    // Oceania
    { code: 'AUS', name: 'Australia', visited: false, continent: 'Oceania' },
    { code: 'FJI', name: 'Fiji', visited: false, continent: 'Oceania' },
    { code: 'KIR', name: 'Kiribati', visited: false, continent: 'Oceania' },
    { code: 'MHL', name: 'Marshall Islands', visited: false, continent: 'Oceania' },
    { code: 'FSM', name: 'Micronesia', visited: false, continent: 'Oceania' },
    { code: 'NRU', name: 'Nauru', visited: false, continent: 'Oceania' },
    { code: 'NZL', name: 'New Zealand', visited: false, continent: 'Oceania' },
    { code: 'PLW', name: 'Palau', visited: false, continent: 'Oceania' },
    { code: 'PNG', name: 'Papua New Guinea', visited: false, continent: 'Oceania' },
    { code: 'WSM', name: 'Samoa', visited: false, continent: 'Oceania' },
    { code: 'SLB', name: 'Solomon Islands', visited: false, continent: 'Oceania' },
    { code: 'TON', name: 'Tonga', visited: false, continent: 'Oceania' },
    { code: 'TUV', name: 'Tuvalu', visited: false, continent: 'Oceania' },
    { code: 'VUT', name: 'Vanuatu', visited: false, continent: 'Oceania' },
  ];
};
